export const adminRepositoryInterface = (repository) => ({
  findAdmin: (email) => repository.findAdmin(email),
  usersCount: () => repository.usersCount(),
  restaurantsCount: () => repository.restaurantsCount(),
  partnersCount: () => repository.partnersCount(),
  saveCategory: (data) => repository.saveCategory(data),
  fetchAllCategory: () => repository.fetchAllCategory(),
  deleteCategory: (id) => repository.deleteCategory(id),
  findCuisine: (cuisine) => repository.findCuisine(cuisine),
  saveCuisine: (newCuisine) => repository.saveCuisine(newCuisine),
  fetchAllCuisines: () => repository.fetchAllCuisines(),
  deleteCuisine: (id) => repository.deleteCuisine(id),
  fetchAllPartners: () => repository.fetchAllPartners(),
  togglePartner: (partner) => repository.togglePartner(partner),
  findPartner: (id) => repository.findPartner(id),
  fetchAllUsers: () => repository.fetchAllUsers(),
  toggleUser: (user) => repository.toggleUser(user),
  findUser: (id) => repository.findUser(id),
  fetchAllRestaurants: () => repository.fetchAllRestaurants(),
  findRestaurant: (id) => repository.findRestaurant(id),
  toggleRestaurant: (restaurant) => repository.toggleRestaurant(restaurant),
});
